<?php

namespace Mic\YcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function findWithFilters($for, $to = "", array $forFilters = array(), array $toFilters = array()) {
		$qb = $this->createQueryBuilder('product');

		$qb->where($qb->expr()->eq("product.name", "'$for'"));
		
		if(count($forFilters) > 0) {
			$qb->join("product.filters", "filters");
			
			foreach($forFilters as $filtre) {
				$qb->andWhere($qb->expr()->eq("filters.name", "'{$filtre['name']}'"));
				$qb->andWhere($qb->expr()->eq("filters.value", "'{$filtre['value']}'"));
			}
		}

		return $qb->getQuery()->getResult();
	}
}
