<?php

namespace Mic\YcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function findWithFilters($for, $to, array $forFilters = array(), array $toFilters = array()) {
		
	}
}
